### ISSUE TITLE
Help DmitryKey get script working

### ISSUE THREAD

**Issue by DmitryKey** [jsjoeio/twitter-stripe-mrr#5]
Hi! Thanks for your script.

I'm trying to launch it and get this:

```node index.js
/Users/dmitrykan/projects/github/twitter-stripe-mrr/index.js:29
  const amountTotal = payouts.data.reduce((a, b) => ({
                                   ^

TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at getStripeRevenue (/Users/dmitrykan/projects/github/twitter-stripe-mrr/index.js:29:36)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async /Users/dmitrykan/projects/github/twitter-stripe-mrr/index.js:78:32
```

Can you give a hint into what could be wrong?

**Comment by jsjoeio** [comment]
Hey @DmitryKey! Yeah, I need to add a null check there. It sounds like `payouts` is coming back possibly empty?

I would throw a `console.log(payouts)` in there and see what's coming back from the Stripe API. If you ran this today, it may be trying to get data between today and April 5, and if you don't have any transactions/sales/etc., then it would make sense that it's null.

Let me know how it goes! Worst case, I could push up a change that would help.

Related:
- https://github.com/jsjoeio/twitter-stripe-mrr/pull/1#issuecomment-807020753

**Comment by DmitryKey** [comment]
Thanks @jsjoeio ! Logging shows it is empty:
```js
{ object: 'list', data: [], has_more: false, url: '/v1/payouts' }
```

I've set the start date to new Date('2021-01-01T00:00:00') and now seeing this error:
```
/Users/dmitrykan/projects/github/twitter-stripe-mrr/index.js:97
    if (err) throw new Error("Failed to update profile")
             ^

Error: Failed to update profile
    at /Users/dmitrykan/projects/github/twitter-stripe-mrr/index.js:97:20
    at Request._callback (/Users/dmitrykan/projects/github/twitter-stripe-mrr/node_modules/twitter/lib/twitter.js:220:14)
    at Request.self.callback (/Users/dmitrykan/projects/github/twitter-stripe-mrr/node_modules/request/request.js:185:22)
    at Request.emit (node:events:369:20)
    at Request.<anonymous> (/Users/dmitrykan/projects/github/twitter-stripe-mrr/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:369:20)
    at IncomingMessage.<anonymous> (/Users/dmitrykan/projects/github/twitter-stripe-mrr/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:475:28)
    at IncomingMessage.emit (node:events:381:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
```

**Comment by jsjoeio** [comment]
> Logging shows it is empty

Sounds like your first issue then!

> if (err) throw new Error("Failed to update profile")

This means something is going wrong when trying to update your profile. The stacktrace doesn't look super helpful. Things that I'd check:
- check that your Twitter auth tokens are set up correctly (did it work before?)
- `console.log(mrrSquares)` - that could be returning a weird result and leading to an error updating your profile location

**Comment by DmitryKey** [comment]
Thanks for your help, indeed it was way too small date range.

The `mrrSquares` print out just fine (the sum is something I need to validate still, but that is easy to check on Stripe side).
I've used this Twitter tokens previously in read-only mode. I've noticed it now and changed to 'Read and write' permission.
There is still the same error, but it may well be that it takes time to apply on Twitter side.

**Comment by DmitryKey** [comment]
I've checked the Stripe amounts and what get's printed via `console.log(payouts)`, and there is a difference.

Stripe amount: 6.73
script's amount: 673

Could this be Stripe API level issue?

**Comment by jsjoeio** [comment]
> There is still the same error, but it may well be that it takes time to apply on Twitter side.

I have some ideas for validating the Twitter tokens.

Really the script should:
- validate environment variables 
- validate the Twitter API + tokens is working as expected
- validate the Stripe API + token is working as expected

I'll see if I can make some changes this week or next.

> Could this be Stripe API level issue?

Interesting...I would say the script is probably the one causing the error lol I'm not sure what that could be though. Which value is correct?

**Comment by DmitryKey** [comment]
6.73 is the correct one.
I've checked a few more values, and there is always a difference of 100x: the value in the script is 100x larger than the real one in Stripe dashboard.

**Comment by jsjoeio** [comment]
Whoops! Probably a case of bad/copy paste. It may be worth me adding a unit test or two as well. Thanks for confirming that!

**Comment by DmitryKey** [comment]
that's a good idea!

I dug through the API and found this!
```
amount
REQUIRED
A positive integer in cents representing how much to payout.
```
in https://stripe.com/docs/api/payouts/create

So it means that actually all amounts *are* in cents => the amount has to be divided by 100 after receiving from the API.

**Comment by jsjoeio** [comment]
Thanks for investigating that. So that explains the difference of 100x 😂

If you'd like, you could submit a PR to fix? Otherwise, I can do it later and give you credit!

**Comment by DmitryKey** [comment]
PR done :)

**Comment by jsjoeio** [comment]
Woo! I'm going to leave this open since you've given me a bunch of other ideas for fixing up the script. I'll let you know when those changes are made.

**Comment by DmitryKey** [comment]
thanks for quick response and support as well @jsjoeio !
Indeed, I still need to figure out the Twitter posting..

**Comment by jsjoeio** [comment]
> validate the Twitter API + tokens is working as expected

Once I had this part in, that should help you!

**Comment by jsjoeio** [comment]
@DmitryKey I started working on this a bit. I've added the validation for environment variables and Twitter. Here's what it looks like:

<img width="424" alt="image" src="https://user-images.githubusercontent.com/3806031/114056251-510ef700-9846-11eb-8568-81a8f4a39d01.png">

See #7. Once I add a few more things and refactor a bit more, I'll merge this in. That should help catch errors sooner.

**Comment by DmitryKey** [comment]
@jsjoeio great addition, makes it more user friendly. I will test this once you merge into main.

**Comment by jsjoeio** [comment]
@DmitryKey I merged #7 which has Stripe validation and it also has support for a dry-run.

Do you mind updating your fork and try running the script `node index.js --dry-run`? This will run everything, but not post to Twitter.

**Comment by DmitryKey** [comment]
@jsjoeio fantastic. Running `main` produces:
<img width="915" alt="Screenshot 2021-04-14 at 23 34 15" src="https://user-images.githubusercontent.com/123553/114775407-eeec4f80-9d79-11eb-8ddb-82b73d61527d.png">
So next challenge to solve is figure out the creds.
I'm thinking to recreate them -- I'm using a Twitter app creds, and when I try to create a new app, Twitter says: "Please apply for a Twitter developer account".

**Comment by jsjoeio** [comment]
Hooray! Waaay better.

Yeah, I believe they changed this a couple years ago. You'll definitely need a Twitter Developer account. Then you'll be able to get the right tokens on a page like this:
![image](https://user-images.githubusercontent.com/3806031/114776257-2087fb00-9d27-11eb-98e3-2befc4a028a6.png)

**Comment by jsjoeio** [comment]
Since I fixed the original error and I don't want to close this until you get it working, I changed the title :)

**Comment by DmitryKey** [comment]
hey @jsjoeio that is totally fine and thanks for keeping the issue open.
I've created new Twitter app and got all access keys and tokens in place.
`--dryRun` works perfectly fine. Then I decided to update the Twitter bio for real. This is what I'm getting right now:


LOG: Found all expected environment variables

✅ Verified your Twitter credentials using follower count.
#️⃣  Your current follower count is 459
✅ Verified your Stripe credentials by creating a PaymentIntent.
💰 A payment intent of 1000 USD was created
💰 Total revenue for month: 14.94

LOG: Calculating MRR squares using goal of 100

⬜ MRR: 0 🟩🟨⬜⬜⬜⬜⬜⬜⬜⬜ 100
Error: HTTP Error: 401 Authorization Required
    at Request._callback (/Users/dmitrykan/projects/github/twitter-stripe-mrr/node_modules/twitter/lib/twitter.js:221:9)
    at Request.self.callback (/Users/dmitrykan/projects/github/twitter-stripe-mrr/node_modules/request/request.js:185:22)
    at Request.emit (node:events:369:20)
    at Request.<anonymous> (/Users/dmitrykan/projects/github/twitter-stripe-mrr/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:369:20)
    at IncomingMessage.<anonymous> (/Users/dmitrykan/projects/github/twitter-stripe-mrr/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:475:28)
    at IncomingMessage.emit (node:events:381:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
/Users/dmitrykan/projects/github/twitter-stripe-mrr/index.js:182
        throw new Error(`\n❌ ERROR: Failed to update Twitter bio location.`)
        ^

Error: 
❌ ERROR: Failed to update Twitter bio location.
    at /Users/dmitrykan/projects/github/twitter-stripe-mrr/index.js:182:15
    at Request._callback (/Users/dmitrykan/projects/github/twitter-stripe-mrr/node_modules/twitter/lib/twitter.js:220:14)
    at Request.self.callback (/Users/dmitrykan/projects/github/twitter-stripe-mrr/node_modules/request/request.js:185:22)
    at Request.emit (node:events:369:20)
    at Request.<anonymous> (/Users/dmitrykan/projects/github/twitter-stripe-mrr/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:369:20)
    at IncomingMessage.<anonymous> (/Users/dmitrykan/projects/github/twitter-stripe-mrr/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:475:28)
    at IncomingMessage.emit (node:events:381:22)
    at endReadableNT (node:internal/streams/readable:1307:12)

**Comment by DmitryKey** [comment]
I figured it! Needed to give the app Write permission and regenerate the Access Token and Secret.
@jsjoeio thanks a bunch for fixing the reported issues! The code became more robust as well, which is super.

**Comment by jsjoeio** [comment]
No worries at all! 

Wow, the logs make it so much easier to debug 🙌

401...guessing your app didn't have the right permissions.

![image](https://user-images.githubusercontent.com/3806031/115276746-497a0880-a0f8-11eb-8739-e74eaadd708d.png)

**Comment by jsjoeio** [comment]
Ah you got it! Woohoo! @DmitryKey glad to hear it :D Closing this for now. 

Feel free to open another issue if you run into anything down the road!
